# Generated by Django 3.2.9 on 2021-11-22 09:05

from django.db import migrations, models

import fitness.document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/')),
            ],
            options={
                'ordering': ('-created_dttm',),
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('image_type', models.CharField(choices=[('profile', 'Profile'), ('on_boarding', 'On Boarding'), ('recipe', 'Recipe'), ('workout', 'Workout'), ('progress', 'Progress'), ('blog', 'Blog')], default='profile', max_length=50)),
                ('file', models.ImageField(upload_to=fitness.document.models.original_upload_handler)),
                ('thumbnail_150', models.ImageField(blank=True, null=True, upload_to=fitness.document.models.thumbnail_upload_handler)),
            ],
            options={
                'ordering': ('-created_dttm',),
            },
        ),
    ]
