# Generated by Django 3.2.9 on 2021-12-18 15:36

from django.db import migrations, models
import fitness.document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('image_type', models.CharField(choices=[('profile', 'Profile'), ('on_boarding', 'On Boarding'), ('recipe', 'Recipe'), ('workout', 'Workout'), ('progress', 'Progress'), ('blog', 'Blog')], default='profile', max_length=50)),
                ('file', models.FileField(upload_to=fitness.document.models.original_upload_handler)),
            ],
            options={
                'ordering': ('-created_dttm',),
            },
        ),
    ]
