# Generated by Django 3.2.9 on 2021-12-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('recipe_category', 'recipe_category'), ('recipe', 'recipe'), ('blog', 'blog'), ('workout', 'workout')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('detail_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('page', 'detail_id')},
            },
        ),
    ]
