# Generated by Django 3.2.9 on 2022-01-26 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read')], default='pending', max_length=15)),
                ('notification_type', models.CharField(choices=[('achievement', 'achievement'), ('journal', 'journal'), ('progress', 'progress'), ('subscription', 'subscription'), ('blog', 'blog')], default='pending', max_length=30)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_dttm',),
                'abstract': False,
            },
        ),
    ]
