# Generated by Django 3.2.9 on 2021-11-30 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211129_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='devices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
