# Generated by Django 3.2.9 on 2021-11-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('social', 'social'), ('email', 'email')], max_length=50, null=True),
        ),
    ]
