# Generated by Django 3.2.9 on 2021-12-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.DurationField(default='7 days'),
        ),
    ]
