# Generated by Django 3.2.9 on 2022-01-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
