# Generated by Django 3.2.9 on 2022-01-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('restricted', 'Restricted')], default='restricted', max_length=50),
        ),
    ]
