# Generated by Django 3.2.9 on 2022-01-26 16:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_settings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('achievement', 'achievement'), ('journal', 'journal'), ('progress', 'progress'), ('subscription', 'subscription'), ('blog', 'blog')], max_length=50), default=['achievement', 'journal', 'progress', 'subscription', 'blog'], size=None),
        ),
    ]
