# Generated by Django 3.2.9 on 2022-01-26 16:36

import django.contrib.postgres.fields
from django.db import migrations, models
import fitness.notification.constants


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_notification_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_settings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('achievement', 'achievement'), ('journal', 'journal'), ('progress', 'progress'), ('subscription', 'subscription'), ('blog', 'blog')], max_length=50), default=fitness.notification.constants.NotificationType.get_default_types, size=None),
        ),
    ]
