# Generated by Django 3.2.9 on 2021-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='version',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
