# Generated by Django 3.2.9 on 2021-12-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
