# Generated by Django 3.2.9 on 2021-12-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quad',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quads', to='workout.gym'),
            preserve_default=False,
        ),
    ]
