# Generated by Django 3.2.9 on 2021-12-23 10:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workoutprogress_workoutresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogress',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='week_duration',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
