# Generated by Django 3.2.9 on 2021-12-23 11:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0004_auto_20211223_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_tracks', to='workout.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gym')},
            },
        ),
        migrations.CreateModel(
            name='QuadTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('data', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('quad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quad_tracks', to='workout.quad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quad_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quad')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='workoutresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workoutresult',
            name='quad',
        ),
        migrations.RemoveField(
            model_name='workoutresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='WorkoutProgress',
        ),
        migrations.DeleteModel(
            name='WorkoutResult',
        ),
    ]
