# Generated by Django 3.2.9 on 2021-12-28 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_auto_20211223_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadtrack',
            name='data',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
