# Generated by Django 3.2.9 on 2022-03-17 09:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_alter_quadtrack_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image',
        ),
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workouttype',
            name='equipment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='workouttype',
            name='min_duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workouttype',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
