# Generated by Django 3.2.9 on 2022-03-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_auto_20220317_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='order_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
