# Generated by Django 3.2.9 on 2022-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_workout_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='min_duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
