# Generated by Django 3.2.9 on 2022-03-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_alter_workouttype_min_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='min_duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
