# Generated by Django 3.2.9 on 2022-03-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_gym_min_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymtrack',
            name='completed_quad_count',
        ),
        migrations.RemoveField(
            model_name='quadtrack',
            name='is_completed',
        ),
    ]
