# Generated by Django 3.2.9 on 2022-01-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_usersubscription_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('updated_dttm', models.DateTimeField(auto_now=True)),
                ('request_data', models.JSONField()),
                ('event_type', models.CharField(max_length=255)),
                ('billing_reason', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-created_dttm',),
                'abstract': False,
            },
        ),
    ]
