# Generated by Django 3.2.9 on 2022-01-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_webhookerrorlog_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookerrorlog',
            name='billing_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='webhookerrorlog',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
